// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	areaFieldNames          = builder.RawFieldNames(&Area{})
	areaRows                = strings.Join(areaFieldNames, ",")
	areaRowsExpectAutoSet   = strings.Join(stringx.Remove(areaFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	areaRowsWithPlaceHolder = strings.Join(stringx.Remove(areaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEdsEnergyAreaIdPrefix = "cache:edsEnergy:area:id:"
)

type (
	areaModel interface {
		Insert(ctx context.Context, data *Area) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Area, error)
		Update(ctx context.Context, data *Area) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAreaModel struct {
		sqlc.CachedConn
		table string
	}

	Area struct {
		Id     int64  `db:"id"`
		Parent int64  `db:"parent"`
		Name   string `db:"name"`
	}
)

func newAreaModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAreaModel {
	return &defaultAreaModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`area`",
	}
}

func (m *defaultAreaModel) Delete(ctx context.Context, id int64) error {
	edsEnergyAreaIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyAreaIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, edsEnergyAreaIdKey)
	return err
}

func (m *defaultAreaModel) FindOne(ctx context.Context, id int64) (*Area, error) {
	edsEnergyAreaIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyAreaIdPrefix, id)
	var resp Area
	err := m.QueryRowCtx(ctx, &resp, edsEnergyAreaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", areaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAreaModel) Insert(ctx context.Context, data *Area) (sql.Result, error) {
	edsEnergyAreaIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyAreaIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, areaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Parent, data.Name)
	}, edsEnergyAreaIdKey)
	return ret, err
}

func (m *defaultAreaModel) Update(ctx context.Context, data *Area) error {
	edsEnergyAreaIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyAreaIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, areaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Parent, data.Name, data.Id)
	}, edsEnergyAreaIdKey)
	return err
}

func (m *defaultAreaModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheEdsEnergyAreaIdPrefix, primary)
}

func (m *defaultAreaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", areaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAreaModel) tableName() string {
	return m.table
}
