// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	carbonFieldNames          = builder.RawFieldNames(&Carbon{})
	carbonRows                = strings.Join(carbonFieldNames, ",")
	carbonRowsExpectAutoSet   = strings.Join(stringx.Remove(carbonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	carbonRowsWithPlaceHolder = strings.Join(stringx.Remove(carbonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEdsEnergyCarbonIdPrefix       = "cache:edsEnergy:carbon:id:"
	cacheEdsEnergyCarbonAreaYearPrefix = "cache:edsEnergy:carbon:area:year:"
)

type (
	carbonModel interface {
		Insert(ctx context.Context, data *Carbon) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Carbon, error)
		FindOneByAreaYear(ctx context.Context, area string, year int64) (*Carbon, error)
		Update(ctx context.Context, data *Carbon) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCarbonModel struct {
		sqlc.CachedConn
		table string
	}

	Carbon struct {
		Id         int64     `db:"id"`
		Area       string    `db:"area"`  // 区域，如全国、华东、福建
		Year       int64     `db:"year"`  // 年份
		Value      float64   `db:"value"` // 碳排因子
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newCarbonModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCarbonModel {
	return &defaultCarbonModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`carbon`",
	}
}

func (m *defaultCarbonModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	edsEnergyCarbonAreaYearKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyCarbonAreaYearPrefix, data.Area, data.Year)
	edsEnergyCarbonIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyCarbonIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, edsEnergyCarbonAreaYearKey, edsEnergyCarbonIdKey)
	return err
}

func (m *defaultCarbonModel) FindOne(ctx context.Context, id int64) (*Carbon, error) {
	edsEnergyCarbonIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyCarbonIdPrefix, id)
	var resp Carbon
	err := m.QueryRowCtx(ctx, &resp, edsEnergyCarbonIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carbonRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarbonModel) FindOneByAreaYear(ctx context.Context, area string, year int64) (*Carbon, error) {
	edsEnergyCarbonAreaYearKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyCarbonAreaYearPrefix, area, year)
	var resp Carbon
	err := m.QueryRowIndexCtx(ctx, &resp, edsEnergyCarbonAreaYearKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `area` = ? and `year` = ? limit 1", carbonRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, area, year); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarbonModel) Insert(ctx context.Context, data *Carbon) (sql.Result, error) {
	edsEnergyCarbonAreaYearKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyCarbonAreaYearPrefix, data.Area, data.Year)
	edsEnergyCarbonIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyCarbonIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, carbonRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Area, data.Year, data.Value)
	}, edsEnergyCarbonAreaYearKey, edsEnergyCarbonIdKey)
	return ret, err
}

func (m *defaultCarbonModel) Update(ctx context.Context, newData *Carbon) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	edsEnergyCarbonAreaYearKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyCarbonAreaYearPrefix, data.Area, data.Year)
	edsEnergyCarbonIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyCarbonIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, carbonRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Area, newData.Year, newData.Value, newData.Id)
	}, edsEnergyCarbonAreaYearKey, edsEnergyCarbonIdKey)
	return err
}

func (m *defaultCarbonModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheEdsEnergyCarbonIdPrefix, primary)
}

func (m *defaultCarbonModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carbonRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCarbonModel) tableName() string {
	return m.table
}
