// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cronFieldNames          = builder.RawFieldNames(&Cron{})
	cronRows                = strings.Join(cronFieldNames, ",")
	cronRowsExpectAutoSet   = strings.Join(stringx.Remove(cronFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cronRowsWithPlaceHolder = strings.Join(stringx.Remove(cronFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEdsEnergyCronIdPrefix = "cache:edsEnergy:cron:id:"
)

type (
	cronModel interface {
		Insert(ctx context.Context, data *Cron) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Cron, error)
		Update(ctx context.Context, data *Cron) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCronModel struct {
		sqlc.CachedConn
		table string
	}

	Cron struct {
		Id         int64     `db:"id"`
		Category   string    `db:"category"`   // 类型：weather,dlgd,holiday,carbon,re-dlgd
		Scheduler  string    `db:"scheduler"`  // 定时(*s *m *h *d *M)
		Task       string    `db:"task"`       // 任务
		Time       string    `db:"time"`       // 时间参数模板
		Comment    string    `db:"comment"`    // 备注
		StartTime  int64     `db:"start_time"` // 生效时间(unix)
		DeltaTime  string    `db:"delta_time"` // 时间间隔(+y,+M,+d,+h,+m,+s)
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newCronModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCronModel {
	return &defaultCronModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`cron`",
	}
}

func (m *defaultCronModel) Delete(ctx context.Context, id int64) error {
	edsEnergyCronIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyCronIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, edsEnergyCronIdKey)
	return err
}

func (m *defaultCronModel) FindOne(ctx context.Context, id int64) (*Cron, error) {
	edsEnergyCronIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyCronIdPrefix, id)
	var resp Cron
	err := m.QueryRowCtx(ctx, &resp, edsEnergyCronIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cronRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCronModel) Insert(ctx context.Context, data *Cron) (sql.Result, error) {
	edsEnergyCronIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyCronIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, cronRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Category, data.Scheduler, data.Task, data.Time, data.Comment, data.StartTime, data.DeltaTime)
	}, edsEnergyCronIdKey)
	return ret, err
}

func (m *defaultCronModel) Update(ctx context.Context, data *Cron) error {
	edsEnergyCronIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyCronIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cronRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Category, data.Scheduler, data.Task, data.Time, data.Comment, data.StartTime, data.DeltaTime, data.Id)
	}, edsEnergyCronIdKey)
	return err
}

func (m *defaultCronModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheEdsEnergyCronIdPrefix, primary)
}

func (m *defaultCronModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cronRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCronModel) tableName() string {
	return m.table
}
