// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dlgdHourFieldNames          = builder.RawFieldNames(&DlgdHour{})
	dlgdHourRows                = strings.Join(dlgdHourFieldNames, ",")
	dlgdHourRowsExpectAutoSet   = strings.Join(stringx.Remove(dlgdHourFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dlgdHourRowsWithPlaceHolder = strings.Join(stringx.Remove(dlgdHourFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEdsCronDlgdHourIdPrefix = "cache:edsCron:dlgdHour:id:"
)

type (
	dlgdHourModel interface {
		Insert(ctx context.Context, data *DlgdHour) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DlgdHour, error)
		Update(ctx context.Context, data *DlgdHour) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDlgdHourModel struct {
		sqlc.CachedConn
		table string
	}

	DlgdHour struct {
		Id            int64  `db:"id"`
		Area          string `db:"area"`           // 区域
		DocNo         string `db:"doc_no"`         // 电价政策文号
		Confirm       int64  `db:"confirm"`        // 确认有效，默认0：未确认
		Name          string `db:"name"`           // 时段名称
		Value         string `db:"value"`          // 时段值
		Temp          string `db:"temp"`           // 温度条件，如：其他月份中广州日最高气温达到35℃
		Months        string `db:"months"`         // 月份条件
		WeekendMonths string `db:"weekend_months"` // 月份-休息日条件
		Holidays      string `db:"holidays"`       // 节假日条件，如：春节,劳动节,国庆节
		Categories    string `db:"categories"`     // 用电类别条件，如：容量315千伏安及以上,两部制
	}
)

func newDlgdHourModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDlgdHourModel {
	return &defaultDlgdHourModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`dlgd_hour`",
	}
}

func (m *defaultDlgdHourModel) Delete(ctx context.Context, id int64) error {
	edsCronDlgdHourIdKey := fmt.Sprintf("%s%v", cacheEdsCronDlgdHourIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, edsCronDlgdHourIdKey)
	return err
}

func (m *defaultDlgdHourModel) FindOne(ctx context.Context, id int64) (*DlgdHour, error) {
	edsCronDlgdHourIdKey := fmt.Sprintf("%s%v", cacheEdsCronDlgdHourIdPrefix, id)
	var resp DlgdHour
	err := m.QueryRowCtx(ctx, &resp, edsCronDlgdHourIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dlgdHourRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDlgdHourModel) Insert(ctx context.Context, data *DlgdHour) (sql.Result, error) {
	edsCronDlgdHourIdKey := fmt.Sprintf("%s%v", cacheEdsCronDlgdHourIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dlgdHourRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Area, data.DocNo, data.Confirm, data.Name, data.Value, data.Temp, data.Months, data.WeekendMonths, data.Holidays, data.Categories)
	}, edsCronDlgdHourIdKey)
	return ret, err
}

func (m *defaultDlgdHourModel) Update(ctx context.Context, data *DlgdHour) error {
	edsCronDlgdHourIdKey := fmt.Sprintf("%s%v", cacheEdsCronDlgdHourIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dlgdHourRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Area, data.DocNo, data.Confirm, data.Name, data.Value, data.Temp, data.Months, data.WeekendMonths, data.Holidays, data.Categories, data.Id)
	}, edsCronDlgdHourIdKey)
	return err
}

func (m *defaultDlgdHourModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheEdsCronDlgdHourIdPrefix, primary)
}

func (m *defaultDlgdHourModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dlgdHourRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDlgdHourModel) tableName() string {
	return m.table
}
