// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	holidayFieldNames          = builder.RawFieldNames(&Holiday{})
	holidayRows                = strings.Join(holidayFieldNames, ",")
	holidayRowsExpectAutoSet   = strings.Join(stringx.Remove(holidayFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	holidayRowsWithPlaceHolder = strings.Join(stringx.Remove(holidayFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEdsEnergyHolidayIdPrefix       = "cache:edsEnergy:holiday:id:"
	cacheEdsEnergyHolidayAreaDatePrefix = "cache:edsEnergy:holiday:area:date:"
)

type (
	holidayModel interface {
		Insert(ctx context.Context, data *Holiday) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Holiday, error)
		FindOneByAreaDate(ctx context.Context, area string, date string) (*Holiday, error)
		Update(ctx context.Context, data *Holiday) error
		Delete(ctx context.Context, id int64) error
	}

	defaultHolidayModel struct {
		sqlc.CachedConn
		table string
	}

	Holiday struct {
		Id         int64     `db:"id"`
		Area       string    `db:"area"` // 地区，如china
		Date       string    `db:"date"` // 日期，如2025-03-18
		Category   string    `db:"category"`
		Detail     string    `db:"detail"` // 假日类型，如元旦
		Alias      string    `db:"alias"`  // 地区别称，如中国
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newHolidayModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultHolidayModel {
	return &defaultHolidayModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`holiday`",
	}
}

func (m *defaultHolidayModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	edsEnergyHolidayAreaDateKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyHolidayAreaDatePrefix, data.Area, data.Date)
	edsEnergyHolidayIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyHolidayIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, edsEnergyHolidayAreaDateKey, edsEnergyHolidayIdKey)
	return err
}

func (m *defaultHolidayModel) FindOne(ctx context.Context, id int64) (*Holiday, error) {
	edsEnergyHolidayIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyHolidayIdPrefix, id)
	var resp Holiday
	err := m.QueryRowCtx(ctx, &resp, edsEnergyHolidayIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", holidayRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHolidayModel) FindOneByAreaDate(ctx context.Context, area string, date string) (*Holiday, error) {
	edsEnergyHolidayAreaDateKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyHolidayAreaDatePrefix, area, date)
	var resp Holiday
	err := m.QueryRowIndexCtx(ctx, &resp, edsEnergyHolidayAreaDateKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `area` = ? and `date` = ? limit 1", holidayRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, area, date); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHolidayModel) Insert(ctx context.Context, data *Holiday) (sql.Result, error) {
	edsEnergyHolidayAreaDateKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyHolidayAreaDatePrefix, data.Area, data.Date)
	edsEnergyHolidayIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyHolidayIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, holidayRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Area, data.Date, data.Category, data.Detail, data.Alias)
	}, edsEnergyHolidayAreaDateKey, edsEnergyHolidayIdKey)
	return ret, err
}

func (m *defaultHolidayModel) Update(ctx context.Context, newData *Holiday) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	edsEnergyHolidayAreaDateKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyHolidayAreaDatePrefix, data.Area, data.Date)
	edsEnergyHolidayIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyHolidayIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, holidayRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Area, newData.Date, newData.Category, newData.Detail, newData.Alias, newData.Id)
	}, edsEnergyHolidayAreaDateKey, edsEnergyHolidayIdKey)
	return err
}

func (m *defaultHolidayModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheEdsEnergyHolidayIdPrefix, primary)
}

func (m *defaultHolidayModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", holidayRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultHolidayModel) tableName() string {
	return m.table
}
