// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	twdlFieldNames          = builder.RawFieldNames(&Twdl{})
	twdlRows                = strings.Join(twdlFieldNames, ",")
	twdlRowsExpectAutoSet   = strings.Join(stringx.Remove(twdlFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	twdlRowsWithPlaceHolder = strings.Join(stringx.Remove(twdlFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEdsCronTwdlIdPrefix                    = "cache:edsCron:twdl:id:"
	cacheEdsCronTwdlStartTimeCategoryDatePrefix = "cache:edsCron:twdl:startTime:category:date:"
)

type (
	twdlModel interface {
		Insert(ctx context.Context, data *Twdl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Twdl, error)
		FindOneByStartTimeCategoryDate(ctx context.Context, startTime time.Time, category string, date string) (*Twdl, error)
		Update(ctx context.Context, data *Twdl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTwdlModel struct {
		sqlc.CachedConn
		table string
	}

	Twdl struct {
		Id                  int64     `db:"id"`
		StartTime           time.Time `db:"start_time"`             // 执行起始时间(含)
		Category            string    `db:"category"`               // 用电类别, 如“低壓電力電價 > 非時間電價"
		Date                string    `db:"date"`                   // 夏月/非夏月日期范围(含首尾), 如"0101-0131,1201-1231"
		Stage               string    `db:"stage"`                  // 阶梯阈值, 只影响基准电价或所有流动电价
		Standard            float64   `db:"standard"`               // 基准电价
		WeekdayPeak         float64   `db:"weekday_peak"`           // 周一至周五尖峰电价
		WeekdaySemiPeak     float64   `db:"weekday_semi_peak"`      // 周一至周五半尖峰电价
		WeekdayOffPeak      float64   `db:"weekday_off_peak"`       // 周一至周五离峰电价
		SatSemiPeak         float64   `db:"sat_semi_peak"`          // 周六半尖峰电价
		SatOffPeak          float64   `db:"sat_off_peak"`           // 周六离峰电价
		SunOffPeak          float64   `db:"sun_off_peak"`           // 周日或离峰日电价
		WeekdayPeakHour     string    `db:"weekday_peak_hour"`      // 周一至周五尖峰时段, 如“0000-2400”
		WeekdaySemiPeakHour string    `db:"weekday_semi_peak_hour"` // 周一至周五半尖峰时段
		WeekdayOffPeakHour  string    `db:"weekday_off_peak_hour"`  // 周一至周五离峰时段
		SatSemiPeakHour     string    `db:"sat_semi_peak_hour"`     // 周六半尖峰时段
		SatOffPeakHour      string    `db:"sat_off_peak_hour"`      // 周六离峰时段
		SunOffPeakHour      string    `db:"sun_off_peak_hour"`      // 周日或离峰日时段
		InstalledCustomer   float64   `db:"installed_customer"`     // [装置契约]按户计收[三相], 默认, 每户每月
		InstalledCustomer1P float64   `db:"installed_customer_1p"`  // [装置契约]按户计收[单相], 每户每月
		RegularCustomer     float64   `db:"regular_customer"`       // [需量契约]按户计收, 每户每月
		InstalledCap        float64   `db:"installed_cap"`          // 装置契约, 每千瓦每月
		RegularCap          float64   `db:"regular_cap"`            // 经常契约，每千瓦每月
		NonSummerCap        float64   `db:"non_summer_cap"`         // 非夏月契约, 每千瓦每月
		SemiPeakCap         float64   `db:"semi_peak_cap"`          // 半尖峰契约, 每千瓦每月
		SatSemiPeakCap      float64   `db:"sat_semi_peak_cap"`      // 周六半尖峰契约, 每千瓦每月
		OffPeakCap          float64   `db:"off_peak_cap"`           // 离峰契约, 每千瓦每月
		CreateTime          time.Time `db:"create_time"`
		UpdateTime          time.Time `db:"update_time"`
	}
)

func newTwdlModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTwdlModel {
	return &defaultTwdlModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`twdl`",
	}
}

func (m *defaultTwdlModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	edsCronTwdlIdKey := fmt.Sprintf("%s%v", cacheEdsCronTwdlIdPrefix, id)
	edsCronTwdlStartTimeCategoryDateKey := fmt.Sprintf("%s%v:%v:%v", cacheEdsCronTwdlStartTimeCategoryDatePrefix, data.StartTime, data.Category, data.Date)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, edsCronTwdlIdKey, edsCronTwdlStartTimeCategoryDateKey)
	return err
}

func (m *defaultTwdlModel) FindOne(ctx context.Context, id int64) (*Twdl, error) {
	edsCronTwdlIdKey := fmt.Sprintf("%s%v", cacheEdsCronTwdlIdPrefix, id)
	var resp Twdl
	err := m.QueryRowCtx(ctx, &resp, edsCronTwdlIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", twdlRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTwdlModel) FindOneByStartTimeCategoryDate(ctx context.Context, startTime time.Time, category string, date string) (*Twdl, error) {
	edsCronTwdlStartTimeCategoryDateKey := fmt.Sprintf("%s%v:%v:%v", cacheEdsCronTwdlStartTimeCategoryDatePrefix, startTime, category, date)
	var resp Twdl
	err := m.QueryRowIndexCtx(ctx, &resp, edsCronTwdlStartTimeCategoryDateKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `start_time` = ? and `category` = ? and `date` = ? limit 1", twdlRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, startTime, category, date); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTwdlModel) Insert(ctx context.Context, data *Twdl) (sql.Result, error) {
	edsCronTwdlIdKey := fmt.Sprintf("%s%v", cacheEdsCronTwdlIdPrefix, data.Id)
	edsCronTwdlStartTimeCategoryDateKey := fmt.Sprintf("%s%v:%v:%v", cacheEdsCronTwdlStartTimeCategoryDatePrefix, data.StartTime, data.Category, data.Date)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, twdlRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.StartTime, data.Category, data.Date, data.Stage, data.Standard, data.WeekdayPeak, data.WeekdaySemiPeak, data.WeekdayOffPeak, data.SatSemiPeak, data.SatOffPeak, data.SunOffPeak, data.WeekdayPeakHour, data.WeekdaySemiPeakHour, data.WeekdayOffPeakHour, data.SatSemiPeakHour, data.SatOffPeakHour, data.SunOffPeakHour, data.InstalledCustomer, data.InstalledCustomer1P, data.RegularCustomer, data.InstalledCap, data.RegularCap, data.NonSummerCap, data.SemiPeakCap, data.SatSemiPeakCap, data.OffPeakCap)
	}, edsCronTwdlIdKey, edsCronTwdlStartTimeCategoryDateKey)
	return ret, err
}

func (m *defaultTwdlModel) Update(ctx context.Context, newData *Twdl) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	edsCronTwdlIdKey := fmt.Sprintf("%s%v", cacheEdsCronTwdlIdPrefix, data.Id)
	edsCronTwdlStartTimeCategoryDateKey := fmt.Sprintf("%s%v:%v:%v", cacheEdsCronTwdlStartTimeCategoryDatePrefix, data.StartTime, data.Category, data.Date)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, twdlRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.StartTime, newData.Category, newData.Date, newData.Stage, newData.Standard, newData.WeekdayPeak, newData.WeekdaySemiPeak, newData.WeekdayOffPeak, newData.SatSemiPeak, newData.SatOffPeak, newData.SunOffPeak, newData.WeekdayPeakHour, newData.WeekdaySemiPeakHour, newData.WeekdayOffPeakHour, newData.SatSemiPeakHour, newData.SatOffPeakHour, newData.SunOffPeakHour, newData.InstalledCustomer, newData.InstalledCustomer1P, newData.RegularCustomer, newData.InstalledCap, newData.RegularCap, newData.NonSummerCap, newData.SemiPeakCap, newData.SatSemiPeakCap, newData.OffPeakCap, newData.Id)
	}, edsCronTwdlIdKey, edsCronTwdlStartTimeCategoryDateKey)
	return err
}

func (m *defaultTwdlModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheEdsCronTwdlIdPrefix, primary)
}

func (m *defaultTwdlModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", twdlRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTwdlModel) tableName() string {
	return m.table
}
