// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	weatherFieldNames          = builder.RawFieldNames(&Weather{})
	weatherRows                = strings.Join(weatherFieldNames, ",")
	weatherRowsExpectAutoSet   = strings.Join(stringx.Remove(weatherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	weatherRowsWithPlaceHolder = strings.Join(stringx.Remove(weatherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheEdsEnergyWeatherIdPrefix       = "cache:edsEnergy:weather:id:"
	cacheEdsEnergyWeatherDateCityPrefix = "cache:edsEnergy:weather:date:city:"
)

type (
	weatherModel interface {
		Insert(ctx context.Context, data *Weather) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Weather, error)
		FindOneByDateCity(ctx context.Context, date string, city string) (*Weather, error)
		Update(ctx context.Context, data *Weather) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWeatherModel struct {
		sqlc.CachedConn
		table string
	}

	Weather struct {
		Id           int64     `db:"id"`
		Date         string    `db:"date"`          // 日期
		City         string    `db:"city"`          // 城市
		DayWeather   string    `db:"day_weather"`   // 白天天气
		DayTemp      float64   `db:"day_temp"`      // 白天气温
		NightWeather string    `db:"night_weather"` // 夜间天气
		NightTemp    float64   `db:"night_temp"`    // 夜间气温
		CreateTime   time.Time `db:"create_time"`
		UpdateTime   time.Time `db:"update_time"`
	}
)

func newWeatherModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultWeatherModel {
	return &defaultWeatherModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`weather`",
	}
}

func (m *defaultWeatherModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	edsEnergyWeatherDateCityKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyWeatherDateCityPrefix, data.Date, data.City)
	edsEnergyWeatherIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyWeatherIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, edsEnergyWeatherDateCityKey, edsEnergyWeatherIdKey)
	return err
}

func (m *defaultWeatherModel) FindOne(ctx context.Context, id int64) (*Weather, error) {
	edsEnergyWeatherIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyWeatherIdPrefix, id)
	var resp Weather
	err := m.QueryRowCtx(ctx, &resp, edsEnergyWeatherIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", weatherRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWeatherModel) FindOneByDateCity(ctx context.Context, date string, city string) (*Weather, error) {
	edsEnergyWeatherDateCityKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyWeatherDateCityPrefix, date, city)
	var resp Weather
	err := m.QueryRowIndexCtx(ctx, &resp, edsEnergyWeatherDateCityKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `date` = ? and `city` = ? limit 1", weatherRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, date, city); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWeatherModel) Insert(ctx context.Context, data *Weather) (sql.Result, error) {
	edsEnergyWeatherDateCityKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyWeatherDateCityPrefix, data.Date, data.City)
	edsEnergyWeatherIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyWeatherIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, weatherRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Date, data.City, data.DayWeather, data.DayTemp, data.NightWeather, data.NightTemp)
	}, edsEnergyWeatherDateCityKey, edsEnergyWeatherIdKey)
	return ret, err
}

func (m *defaultWeatherModel) Update(ctx context.Context, newData *Weather) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	edsEnergyWeatherDateCityKey := fmt.Sprintf("%s%v:%v", cacheEdsEnergyWeatherDateCityPrefix, data.Date, data.City)
	edsEnergyWeatherIdKey := fmt.Sprintf("%s%v", cacheEdsEnergyWeatherIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, weatherRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Date, newData.City, newData.DayWeather, newData.DayTemp, newData.NightWeather, newData.NightTemp, newData.Id)
	}, edsEnergyWeatherDateCityKey, edsEnergyWeatherIdKey)
	return err
}

func (m *defaultWeatherModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheEdsEnergyWeatherIdPrefix, primary)
}

func (m *defaultWeatherModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", weatherRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWeatherModel) tableName() string {
	return m.table
}
