CREATE TABLE IF NOT EXISTS `dlgd` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `area` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '区域',
  `start_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '执行起始时间（含）',
  `end_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '执行截止时间（不含）',
  `category` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '用电分类，如单一制、两部制',
  `voltage` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '电压等级，如1-10（20）千伏',
  `stage` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '阶梯阈值，如深圳',
  `fund` float NOT NULL DEFAULT '0' COMMENT '政府性基金及附加，力调电费需排除',
  `sharp` float NOT NULL DEFAULT '0' COMMENT '尖峰电价',
  `sharp_date` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '尖峰日期',
  `sharp_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '尖峰时段，如1100-1130,2200-0700',
  `peak` float NOT NULL DEFAULT '0' COMMENT '高峰电价',
  `peak_date` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '高峰日期',
  `peak_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '高峰时段',
  `flat` float NOT NULL DEFAULT '0' COMMENT '平段电价',
  `flat_date` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '平段日期',
  `flat_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '平段时段',
  `valley` float NOT NULL DEFAULT '0' COMMENT '低谷电价',
  `valley_date` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '低谷日期',
  `valley_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '低谷时段',
  `deep` float NOT NULL DEFAULT '0' COMMENT '深谷电价',
  `deep_date` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '深谷日期,weekend,holiday:元旦:春节,weather>35',
  `deep_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '深谷时段',
  `demand` float NOT NULL DEFAULT '0' COMMENT '需量电价',
  `capacity` float NOT NULL DEFAULT '0' COMMENT '容量电价',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `area_start_time_category_voltage_stage` (`area`,`start_time`,`category`,`voltage`,`stage`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='代理购电';