CREATE TABLE IF NOT EXISTS `twdl` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `start_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '执行起始时间(含)',
  `category` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '用电类别, 如“低壓電力電價 > 非時間電價"',
  `date` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '夏月/非夏月日期范围(含首尾), 如"0101-0131,1201-1231"',
  `stage` varchar(500) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '阶梯阈值, 只影响基准电价或所有流动电价',
  `standard` float NOT NULL DEFAULT '0' COMMENT '基准电价',
  `weekday_peak` float NOT NULL DEFAULT '0' COMMENT '周一至周五尖峰电价',
  `weekday_semi_peak` float NOT NULL DEFAULT '0' COMMENT '周一至周五半尖峰电价',
  `weekday_off_peak` float NOT NULL DEFAULT '0' COMMENT '周一至周五离峰电价',
  `sat_semi_peak` float NOT NULL DEFAULT '0' COMMENT '周六半尖峰电价',
  `sat_off_peak` float NOT NULL DEFAULT '0' COMMENT '周六离峰电价',
  `sun_off_peak` float NOT NULL DEFAULT '0' COMMENT '周日或离峰日电价',
  `weekday_peak_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '周一至周五尖峰时段, 如“0000-2400”',
  `weekday_semi_peak_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '周一至周五半尖峰时段',
  `weekday_off_peak_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '周一至周五离峰时段',
  `sat_semi_peak_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '周六半尖峰时段',
  `sat_off_peak_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '周六离峰时段',
  `sun_off_peak_hour` varchar(50) COLLATE utf8_bin NOT NULL DEFAULT '0' COMMENT '周日或离峰日时段',
  `installed_customer` float NOT NULL DEFAULT '0' COMMENT '[装置契约]按户计收[三相], 默认, 每户每月',
  `installed_customer_1p` float NOT NULL DEFAULT '0' COMMENT '[装置契约]按户计收[单相], 每户每月',
  `regular_customer` float NOT NULL DEFAULT '0' COMMENT '[需量契约]按户计收, 每户每月',
  `installed_cap` float NOT NULL DEFAULT '0' COMMENT '装置契约, 每千瓦每月',
  `regular_cap` float NOT NULL DEFAULT '0' COMMENT '经常契约，每千瓦每月',
  `non_summer_cap` float NOT NULL DEFAULT '0' COMMENT '非夏月契约, 每千瓦每月',
  `semi_peak_cap` float NOT NULL DEFAULT '0' COMMENT '半尖峰契约, 每千瓦每月',
  `sat_semi_peak_cap` float NOT NULL DEFAULT '0' COMMENT '周六半尖峰契约, 每千瓦每月',
  `off_peak_cap` float NOT NULL DEFAULT '0' COMMENT '离峰契约, 每千瓦每月',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `start_time_category_date` (`start_time`,`category`,`date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='台湾电力';