// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: cron.proto

package server

import (
	"context"

	"seeccloud.com/edscron/cron"
	"seeccloud.com/edscron/internal/logic"
	"seeccloud.com/edscron/internal/svc"
)

type CronServer struct {
	svcCtx *svc.ServiceContext
	cron.UnimplementedCronServer
}

func NewCronServer(svcCtx *svc.ServiceContext) *CronServer {
	return &CronServer{
		svcCtx: svcCtx,
	}
}

// 获取任务列表
func (s *CronServer) GetCrons(ctx context.Context, in *cron.CronsReq) (*cron.CronsRsp, error) {
	l := logic.NewGetCronsLogic(ctx, s.svcCtx)
	return l.GetCrons(in)
}

// 新增任务
func (s *CronServer) AddCron(ctx context.Context, in *cron.CronBody) (*cron.ResultRsp, error) {
	l := logic.NewAddCronLogic(ctx, s.svcCtx)
	return l.AddCron(in)
}

// 更新任务
func (s *CronServer) UpdateCron(ctx context.Context, in *cron.CronBody) (*cron.ResultRsp, error) {
	l := logic.NewUpdateCronLogic(ctx, s.svcCtx)
	return l.UpdateCron(in)
}

// 删除任务
func (s *CronServer) DeleteCron(ctx context.Context, in *cron.DelReq) (*cron.ResultRsp, error) {
	l := logic.NewDeleteCronLogic(ctx, s.svcCtx)
	return l.DeleteCron(in)
}

// 执行任务
func (s *CronServer) TodoCron(ctx context.Context, in *cron.TodoCronReq) (*cron.ResultRsp, error) {
	l := logic.NewTodoCronLogic(ctx, s.svcCtx)
	return l.TodoCron(in)
}

// 获取碳排因子
func (s *CronServer) GetCarbon(ctx context.Context, in *cron.CarbonReq) (*cron.CarbonRsp, error) {
	l := logic.NewGetCarbonLogic(ctx, s.svcCtx)
	return l.GetCarbon(in)
}

// 新增碳排因子
func (s *CronServer) AddCarbon(ctx context.Context, in *cron.AddCarbonReq) (*cron.ResultRsp, error) {
	l := logic.NewAddCarbonLogic(ctx, s.svcCtx)
	return l.AddCarbon(in)
}

// 获取天气预报列表
func (s *CronServer) GetWeathers(ctx context.Context, in *cron.WeathersReq) (*cron.WeathersRsp, error) {
	l := logic.NewGetWeathersLogic(ctx, s.svcCtx)
	return l.GetWeathers(in)
}

// 获取假日列表
func (s *CronServer) GetHolidays(ctx context.Context, in *cron.HolidaysReq) (*cron.HolidaysRsp, error) {
	l := logic.NewGetHolidaysLogic(ctx, s.svcCtx)
	return l.GetHolidays(in)
}

// 新增/更新假日
func (s *CronServer) AddHolidays(ctx context.Context, in *cron.AddHolidaysReq) (*cron.ResultRsp, error) {
	l := logic.NewAddHolidaysLogic(ctx, s.svcCtx)
	return l.AddHolidays(in)
}

// 删除假日
func (s *CronServer) DeleteHoliday(ctx context.Context, in *cron.DelReq) (*cron.ResultRsp, error) {
	l := logic.NewDeleteHolidayLogic(ctx, s.svcCtx)
	return l.DeleteHoliday(in)
}

// 获取电价
func (s *CronServer) GetPrice(ctx context.Context, in *cron.PriceReq) (*cron.PriceRsp, error) {
	l := logic.NewGetPriceLogic(ctx, s.svcCtx)
	return l.GetPrice(in)
}

// 获取账单
func (s *CronServer) GetMonthlyBill(ctx context.Context, in *cron.BillReq) (*cron.BillRsp, error) {
	l := logic.NewGetMonthlyBillLogic(ctx, s.svcCtx)
	return l.GetMonthlyBill(in)
}

// 获取用电档案可选项
func (s *CronServer) GetAvailableOptions(ctx context.Context, in *cron.AvailableOptionsReq) (*cron.AvailableOptionsRsp, error) {
	l := logic.NewGetAvailableOptionsLogic(ctx, s.svcCtx)
	return l.GetAvailableOptions(in)
}

// 获取用电档案
func (s *CronServer) GetUserOption(ctx context.Context, in *cron.GetUserOptionReq) (*cron.UserOptionBody, error) {
	l := logic.NewGetUserOptionLogic(ctx, s.svcCtx)
	return l.GetUserOption(in)
}

// 新增用电档案
func (s *CronServer) AddUserOption(ctx context.Context, in *cron.UserOptionBody) (*cron.ResultRsp, error) {
	l := logic.NewAddUserOptionLogic(ctx, s.svcCtx)
	return l.AddUserOption(in)
}

// 更新用电档案
func (s *CronServer) UpdateUserOption(ctx context.Context, in *cron.UserOptionBody) (*cron.ResultRsp, error) {
	l := logic.NewUpdateUserOptionLogic(ctx, s.svcCtx)
	return l.UpdateUserOption(in)
}

// 删除用电档案
func (s *CronServer) DeleteUserOption(ctx context.Context, in *cron.DelReq) (*cron.ResultRsp, error) {
	l := logic.NewDeleteUserOptionLogic(ctx, s.svcCtx)
	return l.DeleteUserOption(in)
}
