// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: cron.proto

package cron

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CronClient is the client API for Cron service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronClient interface {
	// 获取任务列表
	GetCrons(ctx context.Context, in *CronsReq, opts ...grpc.CallOption) (*CronsRsp, error)
	// 新增任务
	AddCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error)
	// 更新任务
	UpdateCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error)
	// 删除任务
	DeleteCron(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error)
	// 执行任务
	TodoCron(ctx context.Context, in *TodoCronReq, opts ...grpc.CallOption) (*ResultRsp, error)
	// 获取碳排因子
	GetCarbon(ctx context.Context, in *CarbonReq, opts ...grpc.CallOption) (*CarbonRsp, error)
	// 新增碳排因子
	AddCarbon(ctx context.Context, in *AddCarbonReq, opts ...grpc.CallOption) (*ResultRsp, error)
	// 获取天气预报列表
	GetWeathers(ctx context.Context, in *WeathersReq, opts ...grpc.CallOption) (*WeathersRsp, error)
	// 获取假日列表
	GetHolidays(ctx context.Context, in *HolidaysReq, opts ...grpc.CallOption) (*HolidaysRsp, error)
	// 新增/更新假日
	AddHolidays(ctx context.Context, in *AddHolidaysReq, opts ...grpc.CallOption) (*ResultRsp, error)
	// 删除假日
	DeleteHoliday(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error)
	// 获取电价
	GetPrice(ctx context.Context, in *PriceReq, opts ...grpc.CallOption) (*PriceRsp, error)
	// 获取账单
	GetMonthlyBill(ctx context.Context, in *BillReq, opts ...grpc.CallOption) (*BillRsp, error)
	// 获取用电档案可选项
	GetAvailableOptions(ctx context.Context, in *AvailableOptionsReq, opts ...grpc.CallOption) (*AvailableOptionsRsp, error)
	// 获取用电档案
	GetUserOption(ctx context.Context, in *GetUserOptionReq, opts ...grpc.CallOption) (*UserOptionBody, error)
	// 新增用电档案
	AddUserOption(ctx context.Context, in *UserOptionBody, opts ...grpc.CallOption) (*ResultRsp, error)
	// 更新用电档案
	UpdateUserOption(ctx context.Context, in *UserOptionBody, opts ...grpc.CallOption) (*ResultRsp, error)
	// 删除用电档案
	DeleteUserOption(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error)
}

type cronClient struct {
	cc grpc.ClientConnInterface
}

func NewCronClient(cc grpc.ClientConnInterface) CronClient {
	return &cronClient{cc}
}

func (c *cronClient) GetCrons(ctx context.Context, in *CronsReq, opts ...grpc.CallOption) (*CronsRsp, error) {
	out := new(CronsRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/GetCrons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) AddCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/AddCron", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) UpdateCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/UpdateCron", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) DeleteCron(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/DeleteCron", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) TodoCron(ctx context.Context, in *TodoCronReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/TodoCron", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) GetCarbon(ctx context.Context, in *CarbonReq, opts ...grpc.CallOption) (*CarbonRsp, error) {
	out := new(CarbonRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/GetCarbon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) AddCarbon(ctx context.Context, in *AddCarbonReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/AddCarbon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) GetWeathers(ctx context.Context, in *WeathersReq, opts ...grpc.CallOption) (*WeathersRsp, error) {
	out := new(WeathersRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/GetWeathers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) GetHolidays(ctx context.Context, in *HolidaysReq, opts ...grpc.CallOption) (*HolidaysRsp, error) {
	out := new(HolidaysRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/GetHolidays", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) AddHolidays(ctx context.Context, in *AddHolidaysReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/AddHolidays", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) DeleteHoliday(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/DeleteHoliday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) GetPrice(ctx context.Context, in *PriceReq, opts ...grpc.CallOption) (*PriceRsp, error) {
	out := new(PriceRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) GetMonthlyBill(ctx context.Context, in *BillReq, opts ...grpc.CallOption) (*BillRsp, error) {
	out := new(BillRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/GetMonthlyBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) GetAvailableOptions(ctx context.Context, in *AvailableOptionsReq, opts ...grpc.CallOption) (*AvailableOptionsRsp, error) {
	out := new(AvailableOptionsRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/GetAvailableOptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) GetUserOption(ctx context.Context, in *GetUserOptionReq, opts ...grpc.CallOption) (*UserOptionBody, error) {
	out := new(UserOptionBody)
	err := c.cc.Invoke(ctx, "/cron.Cron/GetUserOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) AddUserOption(ctx context.Context, in *UserOptionBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/AddUserOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) UpdateUserOption(ctx context.Context, in *UserOptionBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/UpdateUserOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronClient) DeleteUserOption(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	out := new(ResultRsp)
	err := c.cc.Invoke(ctx, "/cron.Cron/DeleteUserOption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronServer is the server API for Cron service.
// All implementations must embed UnimplementedCronServer
// for forward compatibility
type CronServer interface {
	// 获取任务列表
	GetCrons(context.Context, *CronsReq) (*CronsRsp, error)
	// 新增任务
	AddCron(context.Context, *CronBody) (*ResultRsp, error)
	// 更新任务
	UpdateCron(context.Context, *CronBody) (*ResultRsp, error)
	// 删除任务
	DeleteCron(context.Context, *DelReq) (*ResultRsp, error)
	// 执行任务
	TodoCron(context.Context, *TodoCronReq) (*ResultRsp, error)
	// 获取碳排因子
	GetCarbon(context.Context, *CarbonReq) (*CarbonRsp, error)
	// 新增碳排因子
	AddCarbon(context.Context, *AddCarbonReq) (*ResultRsp, error)
	// 获取天气预报列表
	GetWeathers(context.Context, *WeathersReq) (*WeathersRsp, error)
	// 获取假日列表
	GetHolidays(context.Context, *HolidaysReq) (*HolidaysRsp, error)
	// 新增/更新假日
	AddHolidays(context.Context, *AddHolidaysReq) (*ResultRsp, error)
	// 删除假日
	DeleteHoliday(context.Context, *DelReq) (*ResultRsp, error)
	// 获取电价
	GetPrice(context.Context, *PriceReq) (*PriceRsp, error)
	// 获取账单
	GetMonthlyBill(context.Context, *BillReq) (*BillRsp, error)
	// 获取用电档案可选项
	GetAvailableOptions(context.Context, *AvailableOptionsReq) (*AvailableOptionsRsp, error)
	// 获取用电档案
	GetUserOption(context.Context, *GetUserOptionReq) (*UserOptionBody, error)
	// 新增用电档案
	AddUserOption(context.Context, *UserOptionBody) (*ResultRsp, error)
	// 更新用电档案
	UpdateUserOption(context.Context, *UserOptionBody) (*ResultRsp, error)
	// 删除用电档案
	DeleteUserOption(context.Context, *DelReq) (*ResultRsp, error)
	mustEmbedUnimplementedCronServer()
}

// UnimplementedCronServer must be embedded to have forward compatible implementations.
type UnimplementedCronServer struct {
}

func (UnimplementedCronServer) GetCrons(context.Context, *CronsReq) (*CronsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCrons not implemented")
}
func (UnimplementedCronServer) AddCron(context.Context, *CronBody) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCron not implemented")
}
func (UnimplementedCronServer) UpdateCron(context.Context, *CronBody) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCron not implemented")
}
func (UnimplementedCronServer) DeleteCron(context.Context, *DelReq) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCron not implemented")
}
func (UnimplementedCronServer) TodoCron(context.Context, *TodoCronReq) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TodoCron not implemented")
}
func (UnimplementedCronServer) GetCarbon(context.Context, *CarbonReq) (*CarbonRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCarbon not implemented")
}
func (UnimplementedCronServer) AddCarbon(context.Context, *AddCarbonReq) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCarbon not implemented")
}
func (UnimplementedCronServer) GetWeathers(context.Context, *WeathersReq) (*WeathersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeathers not implemented")
}
func (UnimplementedCronServer) GetHolidays(context.Context, *HolidaysReq) (*HolidaysRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHolidays not implemented")
}
func (UnimplementedCronServer) AddHolidays(context.Context, *AddHolidaysReq) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHolidays not implemented")
}
func (UnimplementedCronServer) DeleteHoliday(context.Context, *DelReq) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHoliday not implemented")
}
func (UnimplementedCronServer) GetPrice(context.Context, *PriceReq) (*PriceRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedCronServer) GetMonthlyBill(context.Context, *BillReq) (*BillRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyBill not implemented")
}
func (UnimplementedCronServer) GetAvailableOptions(context.Context, *AvailableOptionsReq) (*AvailableOptionsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableOptions not implemented")
}
func (UnimplementedCronServer) GetUserOption(context.Context, *GetUserOptionReq) (*UserOptionBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOption not implemented")
}
func (UnimplementedCronServer) AddUserOption(context.Context, *UserOptionBody) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserOption not implemented")
}
func (UnimplementedCronServer) UpdateUserOption(context.Context, *UserOptionBody) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserOption not implemented")
}
func (UnimplementedCronServer) DeleteUserOption(context.Context, *DelReq) (*ResultRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserOption not implemented")
}
func (UnimplementedCronServer) mustEmbedUnimplementedCronServer() {}

// UnsafeCronServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronServer will
// result in compilation errors.
type UnsafeCronServer interface {
	mustEmbedUnimplementedCronServer()
}

func RegisterCronServer(s grpc.ServiceRegistrar, srv CronServer) {
	s.RegisterService(&Cron_ServiceDesc, srv)
}

func _Cron_GetCrons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetCrons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/GetCrons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetCrons(ctx, req.(*CronsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_AddCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).AddCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/AddCron",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).AddCron(ctx, req.(*CronBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_UpdateCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).UpdateCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/UpdateCron",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).UpdateCron(ctx, req.(*CronBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_DeleteCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).DeleteCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/DeleteCron",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).DeleteCron(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_TodoCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoCronReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).TodoCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/TodoCron",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).TodoCron(ctx, req.(*TodoCronReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_GetCarbon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarbonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetCarbon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/GetCarbon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetCarbon(ctx, req.(*CarbonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_AddCarbon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCarbonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).AddCarbon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/AddCarbon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).AddCarbon(ctx, req.(*AddCarbonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_GetWeathers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeathersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetWeathers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/GetWeathers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetWeathers(ctx, req.(*WeathersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_GetHolidays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HolidaysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetHolidays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/GetHolidays",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetHolidays(ctx, req.(*HolidaysReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_AddHolidays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHolidaysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).AddHolidays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/AddHolidays",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).AddHolidays(ctx, req.(*AddHolidaysReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_DeleteHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).DeleteHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/DeleteHoliday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).DeleteHoliday(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetPrice(ctx, req.(*PriceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_GetMonthlyBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetMonthlyBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/GetMonthlyBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetMonthlyBill(ctx, req.(*BillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_GetAvailableOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableOptionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetAvailableOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/GetAvailableOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetAvailableOptions(ctx, req.(*AvailableOptionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_GetUserOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOptionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).GetUserOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/GetUserOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).GetUserOption(ctx, req.(*GetUserOptionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_AddUserOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOptionBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).AddUserOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/AddUserOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).AddUserOption(ctx, req.(*UserOptionBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_UpdateUserOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOptionBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).UpdateUserOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/UpdateUserOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).UpdateUserOption(ctx, req.(*UserOptionBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cron_DeleteUserOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServer).DeleteUserOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cron.Cron/DeleteUserOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServer).DeleteUserOption(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Cron_ServiceDesc is the grpc.ServiceDesc for Cron service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cron_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cron.Cron",
	HandlerType: (*CronServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCrons",
			Handler:    _Cron_GetCrons_Handler,
		},
		{
			MethodName: "AddCron",
			Handler:    _Cron_AddCron_Handler,
		},
		{
			MethodName: "UpdateCron",
			Handler:    _Cron_UpdateCron_Handler,
		},
		{
			MethodName: "DeleteCron",
			Handler:    _Cron_DeleteCron_Handler,
		},
		{
			MethodName: "TodoCron",
			Handler:    _Cron_TodoCron_Handler,
		},
		{
			MethodName: "GetCarbon",
			Handler:    _Cron_GetCarbon_Handler,
		},
		{
			MethodName: "AddCarbon",
			Handler:    _Cron_AddCarbon_Handler,
		},
		{
			MethodName: "GetWeathers",
			Handler:    _Cron_GetWeathers_Handler,
		},
		{
			MethodName: "GetHolidays",
			Handler:    _Cron_GetHolidays_Handler,
		},
		{
			MethodName: "AddHolidays",
			Handler:    _Cron_AddHolidays_Handler,
		},
		{
			MethodName: "DeleteHoliday",
			Handler:    _Cron_DeleteHoliday_Handler,
		},
		{
			MethodName: "GetPrice",
			Handler:    _Cron_GetPrice_Handler,
		},
		{
			MethodName: "GetMonthlyBill",
			Handler:    _Cron_GetMonthlyBill_Handler,
		},
		{
			MethodName: "GetAvailableOptions",
			Handler:    _Cron_GetAvailableOptions_Handler,
		},
		{
			MethodName: "GetUserOption",
			Handler:    _Cron_GetUserOption_Handler,
		},
		{
			MethodName: "AddUserOption",
			Handler:    _Cron_AddUserOption_Handler,
		},
		{
			MethodName: "UpdateUserOption",
			Handler:    _Cron_UpdateUserOption_Handler,
		},
		{
			MethodName: "DeleteUserOption",
			Handler:    _Cron_DeleteUserOption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cron.proto",
}
