// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: cron.proto

package cron

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //
}

func (x *DelReq) Reset() {
	*x = DelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelReq) ProtoMessage() {}

func (x *DelReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelReq.ProtoReflect.Descriptor instead.
func (*DelReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{0}
}

func (x *DelReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResultRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` //
}

func (x *ResultRsp) Reset() {
	*x = ResultRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRsp) ProtoMessage() {}

func (x *ResultRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRsp.ProtoReflect.Descriptor instead.
func (*ResultRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{1}
}

func (x *ResultRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 快速开始
type QuickStartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // 用户地址
}

func (x *QuickStartReq) Reset() {
	*x = QuickStartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuickStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickStartReq) ProtoMessage() {}

func (x *QuickStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickStartReq.ProtoReflect.Descriptor instead.
func (*QuickStartReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{2}
}

func (x *QuickStartReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CronBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category  string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`    // 任务类别，如："dlgd","holiday","weather","carbon"
	Scheduler string `protobuf:"bytes,2,opt,name=scheduler,proto3" json:"scheduler,omitempty"`  // 触发时间，按cron表达式解析
	Task      string `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`            // 任务详情，json格式
	Time      string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`            // 时间参数，用任务目标时间代替task中存在的时间参数
	Comment   string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`      // 备注说明
	StartTime int64  `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"` // 起始时间，在此之前任务不会执行
	DeltaTime string `protobuf:"bytes,7,opt,name=deltaTime,proto3" json:"deltaTime,omitempty"`  // 下期任务时间间隔，格式如“y,d,M,h,m,s”
	Id        int64  `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`               //
}

func (x *CronBody) Reset() {
	*x = CronBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronBody) ProtoMessage() {}

func (x *CronBody) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronBody.ProtoReflect.Descriptor instead.
func (*CronBody) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{3}
}

func (x *CronBody) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CronBody) GetScheduler() string {
	if x != nil {
		return x.Scheduler
	}
	return ""
}

func (x *CronBody) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *CronBody) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *CronBody) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CronBody) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CronBody) GetDeltaTime() string {
	if x != nil {
		return x.DeltaTime
	}
	return ""
}

func (x *CronBody) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CronsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CronsReq) Reset() {
	*x = CronsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronsReq) ProtoMessage() {}

func (x *CronsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronsReq.ProtoReflect.Descriptor instead.
func (*CronsReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{4}
}

type CronsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crons []*CronBody `protobuf:"bytes,1,rep,name=crons,proto3" json:"crons,omitempty"` // 任务列表
}

func (x *CronsRsp) Reset() {
	*x = CronsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CronsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronsRsp) ProtoMessage() {}

func (x *CronsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronsRsp.ProtoReflect.Descriptor instead.
func (*CronsRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{5}
}

func (x *CronsRsp) GetCrons() []*CronBody {
	if x != nil {
		return x.Crons
	}
	return nil
}

type TodoCronReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 任务ID
	Time string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"` // 任务目标时间
}

func (x *TodoCronReq) Reset() {
	*x = TodoCronReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoCronReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoCronReq) ProtoMessage() {}

func (x *TodoCronReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoCronReq.ProtoReflect.Descriptor instead.
func (*TodoCronReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{6}
}

func (x *TodoCronReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoCronReq) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type CarbonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 用户地址
	Year    int64  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`      //
}

func (x *CarbonReq) Reset() {
	*x = CarbonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarbonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarbonReq) ProtoMessage() {}

func (x *CarbonReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarbonReq.ProtoReflect.Descriptor instead.
func (*CarbonReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{7}
}

func (x *CarbonReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CarbonReq) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

type CarbonRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"` //
}

func (x *CarbonRsp) Reset() {
	*x = CarbonRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarbonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarbonRsp) ProtoMessage() {}

func (x *CarbonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarbonRsp.ProtoReflect.Descriptor instead.
func (*CarbonRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{8}
}

func (x *CarbonRsp) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddCarbonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area  string  `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`     //
	Year  int64   `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`    //
	Value float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"` //
}

func (x *AddCarbonReq) Reset() {
	*x = AddCarbonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCarbonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCarbonReq) ProtoMessage() {}

func (x *AddCarbonReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCarbonReq.ProtoReflect.Descriptor instead.
func (*AddCarbonReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{9}
}

func (x *AddCarbonReq) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *AddCarbonReq) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AddCarbonReq) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type WeathersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 用户地址
	Date    string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`       // 开始日期
	Size    int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`      // 获取天数
}

func (x *WeathersReq) Reset() {
	*x = WeathersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeathersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeathersReq) ProtoMessage() {}

func (x *WeathersReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeathersReq.ProtoReflect.Descriptor instead.
func (*WeathersReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{10}
}

func (x *WeathersReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WeathersReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *WeathersReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Weather struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date         string  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                 //
	DayWeather   string  `protobuf:"bytes,2,opt,name=dayWeather,proto3" json:"dayWeather,omitempty"`     // 白日天气
	DayTemp      float64 `protobuf:"fixed64,3,opt,name=dayTemp,proto3" json:"dayTemp,omitempty"`         // 白日气温
	NightWeather string  `protobuf:"bytes,4,opt,name=nightWeather,proto3" json:"nightWeather,omitempty"` // 夜间天气
	NightTemp    float64 `protobuf:"fixed64,5,opt,name=nightTemp,proto3" json:"nightTemp,omitempty"`     // 夜间气温
}

func (x *Weather) Reset() {
	*x = Weather{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{11}
}

func (x *Weather) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Weather) GetDayWeather() string {
	if x != nil {
		return x.DayWeather
	}
	return ""
}

func (x *Weather) GetDayTemp() float64 {
	if x != nil {
		return x.DayTemp
	}
	return 0
}

func (x *Weather) GetNightWeather() string {
	if x != nil {
		return x.NightWeather
	}
	return ""
}

func (x *Weather) GetNightTemp() float64 {
	if x != nil {
		return x.NightTemp
	}
	return 0
}

type WeathersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weathers []*Weather `protobuf:"bytes,1,rep,name=weathers,proto3" json:"weathers,omitempty"` //
}

func (x *WeathersRsp) Reset() {
	*x = WeathersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeathersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeathersRsp) ProtoMessage() {}

func (x *WeathersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeathersRsp.ProtoReflect.Descriptor instead.
func (*WeathersRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{12}
}

func (x *WeathersRsp) GetWeathers() []*Weather {
	if x != nil {
		return x.Weathers
	}
	return nil
}

type HolidaysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 用户地址
	Year    int64  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`      //
}

func (x *HolidaysReq) Reset() {
	*x = HolidaysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolidaysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidaysReq) ProtoMessage() {}

func (x *HolidaysReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidaysReq.ProtoReflect.Descriptor instead.
func (*HolidaysReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{13}
}

func (x *HolidaysReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HolidaysReq) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Holiday struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            //
	Date     string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`         //
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // 假日类别：假日、调休工作日
	Detail   string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`     //
}

func (x *Holiday) Reset() {
	*x = Holiday{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Holiday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holiday) ProtoMessage() {}

func (x *Holiday) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holiday.ProtoReflect.Descriptor instead.
func (*Holiday) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{14}
}

func (x *Holiday) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Holiday) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Holiday) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Holiday) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type HolidaysRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Holidays []*Holiday `protobuf:"bytes,1,rep,name=holidays,proto3" json:"holidays,omitempty"` //
}

func (x *HolidaysRsp) Reset() {
	*x = HolidaysRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolidaysRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidaysRsp) ProtoMessage() {}

func (x *HolidaysRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidaysRsp.ProtoReflect.Descriptor instead.
func (*HolidaysRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{15}
}

func (x *HolidaysRsp) GetHolidays() []*Holiday {
	if x != nil {
		return x.Holidays
	}
	return nil
}

type AddHolidaysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`   // 用户地址
	Holidays []*Holiday `protobuf:"bytes,2,rep,name=holidays,proto3" json:"holidays,omitempty"` //
}

func (x *AddHolidaysReq) Reset() {
	*x = AddHolidaysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHolidaysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHolidaysReq) ProtoMessage() {}

func (x *AddHolidaysReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHolidaysReq.ProtoReflect.Descriptor instead.
func (*AddHolidaysReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{16}
}

func (x *AddHolidaysReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddHolidaysReq) GetHolidays() []*Holiday {
	if x != nil {
		return x.Holidays
	}
	return nil
}

type PriceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // 用电类别，例："福建>工商业,两部制>1-10（20）千伏"
	Time     string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`         // 时间节点，例："2025-08-01 00:00:00"
}

func (x *PriceReq) Reset() {
	*x = PriceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceReq) ProtoMessage() {}

func (x *PriceReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceReq.ProtoReflect.Descriptor instead.
func (*PriceReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{17}
}

func (x *PriceReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PriceReq) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type PriceRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // 所属时段，例："flat"
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"` // 时段电价，例：1.0
	Desc  string  `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`     // 时段描述，例："平段"
	Color string  `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`   // 时段色块，例："#3498DB"
}

func (x *PriceRsp) Reset() {
	*x = PriceRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRsp) ProtoMessage() {}

func (x *PriceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRsp.ProtoReflect.Descriptor instead.
func (*PriceRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{18}
}

func (x *PriceRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PriceRsp) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceRsp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PriceRsp) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type BillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string    `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`        // 工程ID
	Area    string    `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`              // 工程区域，可选区域名、支路名或设备ID等关键字，sql用like查询
	Month   string    `protobuf:"bytes,3,opt,name=month,proto3" json:"month,omitempty"`            // 按月查询，例："2025-08"
	Ep30Ms  []float64 `protobuf:"fixed64,4,rep,packed,name=ep30ms,proto3" json:"ep30ms,omitempty"` // 30min有功电能列表
	EqTotal float64   `protobuf:"fixed64,5,opt,name=eqTotal,proto3" json:"eqTotal,omitempty"`      // 总无功电能，计算功率因素调整电费
}

func (x *BillReq) Reset() {
	*x = BillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillReq) ProtoMessage() {}

func (x *BillReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillReq.ProtoReflect.Descriptor instead.
func (*BillReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{19}
}

func (x *BillReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BillReq) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *BillReq) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *BillReq) GetEp30Ms() []float64 {
	if x != nil {
		return x.Ep30Ms
	}
	return nil
}

func (x *BillReq) GetEqTotal() float64 {
	if x != nil {
		return x.EqTotal
	}
	return 0
}

type BillDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // 所属时段，例："flat"
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"` // 时段电价，例：1.0
	Desc  string  `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`     // 时段描述，例："平段"
	Color string  `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`   // 时段色块，例："#3498DB"
	Usage float64 `protobuf:"fixed64,5,opt,name=usage,proto3" json:"usage,omitempty"` // 所用电量，例：100.0
}

func (x *BillDetail) Reset() {
	*x = BillDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillDetail) ProtoMessage() {}

func (x *BillDetail) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillDetail.ProtoReflect.Descriptor instead.
func (*BillDetail) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{20}
}

func (x *BillDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BillDetail) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BillDetail) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *BillDetail) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *BillDetail) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type BillRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee      float64       `protobuf:"fixed64,1,opt,name=fee,proto3" json:"fee,omitempty"`           // 本期电费
	BasicFee float64       `protobuf:"fixed64,2,opt,name=basicFee,proto3" json:"basicFee,omitempty"` // 基础电费
	UsageFee float64       `protobuf:"fixed64,3,opt,name=usageFee,proto3" json:"usageFee,omitempty"` // 电量电费
	PfFee    float64       `protobuf:"fixed64,4,opt,name=pfFee,proto3" json:"pfFee,omitempty"`       // 功率因素调整电费
	StageFee float64       `protobuf:"fixed64,5,opt,name=stageFee,proto3" json:"stageFee,omitempty"` // 阶梯电费
	Usage    float64       `protobuf:"fixed64,6,opt,name=usage,proto3" json:"usage,omitempty"`       // 本期电量
	Details  []*BillDetail `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty"`     // 峰谷分时电量电费列表
}

func (x *BillRsp) Reset() {
	*x = BillRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillRsp) ProtoMessage() {}

func (x *BillRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillRsp.ProtoReflect.Descriptor instead.
func (*BillRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{21}
}

func (x *BillRsp) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *BillRsp) GetBasicFee() float64 {
	if x != nil {
		return x.BasicFee
	}
	return 0
}

func (x *BillRsp) GetUsageFee() float64 {
	if x != nil {
		return x.UsageFee
	}
	return 0
}

func (x *BillRsp) GetPfFee() float64 {
	if x != nil {
		return x.PfFee
	}
	return 0
}

func (x *BillRsp) GetStageFee() float64 {
	if x != nil {
		return x.StageFee
	}
	return 0
}

func (x *BillRsp) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *BillRsp) GetDetails() []*BillDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

type AvailableOptionsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 工程地址，需包含省份、城市、区县信息，示例："福建省厦门市集美区孙坂南路92号"
}

func (x *AvailableOptionsReq) Reset() {
	*x = AvailableOptionsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableOptionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableOptionsReq) ProtoMessage() {}

func (x *AvailableOptionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableOptionsReq.ProtoReflect.Descriptor instead.
func (*AvailableOptionsReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{22}
}

func (x *AvailableOptionsReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AvailableOptionsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories   []string  `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`              // 用电类别列表，示例：["福建>工商业,两部制>1-10（20）千伏"]
	PowerFactors []float64 `protobuf:"fixed64,2,rep,packed,name=powerFactors,proto3" json:"powerFactors,omitempty"` // 功率因素标准值列表，示例：[0.8, 0.85, 0.9]
}

func (x *AvailableOptionsRsp) Reset() {
	*x = AvailableOptionsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableOptionsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableOptionsRsp) ProtoMessage() {}

func (x *AvailableOptionsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableOptionsRsp.ProtoReflect.Descriptor instead.
func (*AvailableOptionsRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{23}
}

func (x *AvailableOptionsRsp) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *AvailableOptionsRsp) GetPowerFactors() []float64 {
	if x != nil {
		return x.PowerFactors
	}
	return nil
}

type GetUserOptionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // 工程ID
	Area    string `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`       // 工程区域，可选区域名、支路名或设备ID等关键字，sql用like查询
}

func (x *GetUserOptionReq) Reset() {
	*x = GetUserOptionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOptionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOptionReq) ProtoMessage() {}

func (x *GetUserOptionReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOptionReq.ProtoReflect.Descriptor instead.
func (*GetUserOptionReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserOptionReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetUserOptionReq) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type UserOptionBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account        string  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                  // 工程ID
	Area           string  `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`                        // 工程区域
	Category       string  `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                // 用电类别
	PowerFactor    float64 `protobuf:"fixed64,4,opt,name=powerFactor,proto3" json:"powerFactor,omitempty"`        // [大陆]功率因素标准
	Capacity       float64 `protobuf:"fixed64,5,opt,name=capacity,proto3" json:"capacity,omitempty"`              // [大陆]合同容量
	Demand         float64 `protobuf:"fixed64,6,opt,name=demand,proto3" json:"demand,omitempty"`                  // [大陆]合同需量
	InstalledCap   float64 `protobuf:"fixed64,7,opt,name=installedCap,proto3" json:"installedCap,omitempty"`      // [台湾]装置契约
	RegularCap     float64 `protobuf:"fixed64,8,opt,name=regularCap,proto3" json:"regularCap,omitempty"`          // [台湾]常规契约
	NonSummerCap   float64 `protobuf:"fixed64,9,opt,name=nonSummerCap,proto3" json:"nonSummerCap,omitempty"`      // [台湾]非夏季契约
	SemiPeakCap    float64 `protobuf:"fixed64,10,opt,name=semiPeakCap,proto3" json:"semiPeakCap,omitempty"`       // [台湾]半尖峰契约
	SatSemiPeakCap float64 `protobuf:"fixed64,11,opt,name=satSemiPeakCap,proto3" json:"satSemiPeakCap,omitempty"` // [台湾]周六半尖峰契约
	OffPeakCap     float64 `protobuf:"fixed64,12,opt,name=offPeakCap,proto3" json:"offPeakCap,omitempty"`         // [台湾]离峰契约
	Id             int64   `protobuf:"varint,13,opt,name=id,proto3" json:"id,omitempty"`                          //
}

func (x *UserOptionBody) Reset() {
	*x = UserOptionBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOptionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOptionBody) ProtoMessage() {}

func (x *UserOptionBody) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOptionBody.ProtoReflect.Descriptor instead.
func (*UserOptionBody) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{25}
}

func (x *UserOptionBody) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserOptionBody) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *UserOptionBody) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UserOptionBody) GetPowerFactor() float64 {
	if x != nil {
		return x.PowerFactor
	}
	return 0
}

func (x *UserOptionBody) GetCapacity() float64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *UserOptionBody) GetDemand() float64 {
	if x != nil {
		return x.Demand
	}
	return 0
}

func (x *UserOptionBody) GetInstalledCap() float64 {
	if x != nil {
		return x.InstalledCap
	}
	return 0
}

func (x *UserOptionBody) GetRegularCap() float64 {
	if x != nil {
		return x.RegularCap
	}
	return 0
}

func (x *UserOptionBody) GetNonSummerCap() float64 {
	if x != nil {
		return x.NonSummerCap
	}
	return 0
}

func (x *UserOptionBody) GetSemiPeakCap() float64 {
	if x != nil {
		return x.SemiPeakCap
	}
	return 0
}

func (x *UserOptionBody) GetSatSemiPeakCap() float64 {
	if x != nil {
		return x.SatSemiPeakCap
	}
	return 0
}

func (x *UserOptionBody) GetOffPeakCap() float64 {
	if x != nil {
		return x.OffPeakCap
	}
	return 0
}

func (x *UserOptionBody) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddDlgdHourReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`       // 区域
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"` // 原始文本
}

func (x *AddDlgdHourReq) Reset() {
	*x = AddDlgdHourReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDlgdHourReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDlgdHourReq) ProtoMessage() {}

func (x *AddDlgdHourReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDlgdHourReq.ProtoReflect.Descriptor instead.
func (*AddDlgdHourReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{26}
}

func (x *AddDlgdHourReq) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *AddDlgdHourReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type DlgdHourReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area  string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`   // 区域
	DocNo string `protobuf:"bytes,2,opt,name=docNo,proto3" json:"docNo,omitempty"` // 政策文号
}

func (x *DlgdHourReq) Reset() {
	*x = DlgdHourReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DlgdHourReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlgdHourReq) ProtoMessage() {}

func (x *DlgdHourReq) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlgdHourReq.ProtoReflect.Descriptor instead.
func (*DlgdHourReq) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{27}
}

func (x *DlgdHourReq) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *DlgdHourReq) GetDocNo() string {
	if x != nil {
		return x.DocNo
	}
	return ""
}

type DlgdHour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area          string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`                   // 区域
	DocNo         string `protobuf:"bytes,2,opt,name=docNo,proto3" json:"docNo,omitempty"`                 // 政策文号
	Confirm       int64  `protobuf:"varint,3,opt,name=confirm,proto3" json:"confirm,omitempty"`            // 确认有效
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                   // 时段名称
	Value         string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`                 // 时段值
	Temp          string `protobuf:"bytes,6,opt,name=temp,proto3" json:"temp,omitempty"`                   // 温度条件，如：其他月份中广州日最高气温达到35℃
	Months        string `protobuf:"bytes,7,opt,name=months,proto3" json:"months,omitempty"`               // 月份条件
	WeekendMonths string `protobuf:"bytes,8,opt,name=weekendMonths,proto3" json:"weekendMonths,omitempty"` // 月份-休息日条件
	Holidays      string `protobuf:"bytes,9,opt,name=holidays,proto3" json:"holidays,omitempty"`           // 节假日条件，如：春节,劳动节,国庆节
	Categories    string `protobuf:"bytes,10,opt,name=categories,proto3" json:"categories,omitempty"`      // 用电类别条件，如：容量315千伏安及以上,两部制
}

func (x *DlgdHour) Reset() {
	*x = DlgdHour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DlgdHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlgdHour) ProtoMessage() {}

func (x *DlgdHour) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlgdHour.ProtoReflect.Descriptor instead.
func (*DlgdHour) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{28}
}

func (x *DlgdHour) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *DlgdHour) GetDocNo() string {
	if x != nil {
		return x.DocNo
	}
	return ""
}

func (x *DlgdHour) GetConfirm() int64 {
	if x != nil {
		return x.Confirm
	}
	return 0
}

func (x *DlgdHour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DlgdHour) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DlgdHour) GetTemp() string {
	if x != nil {
		return x.Temp
	}
	return ""
}

func (x *DlgdHour) GetMonths() string {
	if x != nil {
		return x.Months
	}
	return ""
}

func (x *DlgdHour) GetWeekendMonths() string {
	if x != nil {
		return x.WeekendMonths
	}
	return ""
}

func (x *DlgdHour) GetHolidays() string {
	if x != nil {
		return x.Holidays
	}
	return ""
}

func (x *DlgdHour) GetCategories() string {
	if x != nil {
		return x.Categories
	}
	return ""
}

type DlgdHoursRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hours []*DlgdHour `protobuf:"bytes,1,rep,name=hours,proto3" json:"hours,omitempty"` // 用电时段列表
}

func (x *DlgdHoursRsp) Reset() {
	*x = DlgdHoursRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cron_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DlgdHoursRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlgdHoursRsp) ProtoMessage() {}

func (x *DlgdHoursRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlgdHoursRsp.ProtoReflect.Descriptor instead.
func (*DlgdHoursRsp) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{29}
}

func (x *DlgdHoursRsp) GetHours() []*DlgdHour {
	if x != nil {
		return x.Hours
	}
	return nil
}

var File_cron_proto protoreflect.FileDescriptor

var file_cron_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x72,
	0x6f, 0x6e, 0x22, 0x18, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x09,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xd2,
	0x01, 0x0a, 0x08, 0x43, 0x72, 0x6f, 0x6e, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x0a, 0x0a, 0x08, 0x43, 0x72, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x22,
	0x30, 0x0a, 0x08, 0x43, 0x72, 0x6f, 0x6e, 0x73, 0x52, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x05, 0x63,
	0x72, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x72, 0x6f,
	0x6e, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x05, 0x63, 0x72, 0x6f, 0x6e,
	0x73, 0x22, 0x31, 0x0a, 0x0b, 0x54, 0x6f, 0x64, 0x6f, 0x43, 0x72, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x79,
	0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22,
	0x21, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x4c, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x4f, 0x0a, 0x0b, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x22, 0x99, 0x01, 0x0a, 0x07, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x79, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x79, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x64, 0x61, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x6e,
	0x69, 0x67, 0x68, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x22, 0x38, 0x0a,
	0x0b, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x08,
	0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x08, 0x77,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x73, 0x22, 0x3b, 0x0a, 0x0b, 0x48, 0x6f, 0x6c, 0x69, 0x64,
	0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x22, 0x61, 0x0a, 0x07, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x38, 0x0a, 0x0b, 0x48, 0x6f, 0x6c, 0x69, 0x64,
	0x61, 0x79, 0x73, 0x52, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x08, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61,
	0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e,
	0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x52, 0x08, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79,
	0x73, 0x22, 0x55, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a,
	0x08, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x52, 0x08,
	0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x22, 0x3a, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x7f, 0x0a, 0x07, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x6e, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x70, 0x33, 0x30, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x06, 0x65, 0x70, 0x33, 0x30, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x71, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x65, 0x71,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x76, 0x0a, 0x0a, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22, 0xc7, 0x01,
	0x0a, 0x07, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x46, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x46, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x46, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x46, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x66, 0x46, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x66, 0x46, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x46, 0x65, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x46, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x72, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x2f, 0x0a, 0x13, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x59, 0x0a, 0x13, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x73, 0x70, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0c, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x46, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x22, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x65, 0x61, 0x22, 0x92, 0x03, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x46, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x46, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x65, 0x64, 0x43, 0x61, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x43, 0x61, 0x70, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x43, 0x61, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0a, 0x72, 0x65, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x43, 0x61, 0x70, 0x12, 0x22, 0x0a, 0x0c,
	0x6e, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x43, 0x61, 0x70, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0c, 0x6e, 0x6f, 0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x43, 0x61, 0x70,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x6d, 0x69, 0x50, 0x65, 0x61, 0x6b, 0x43, 0x61, 0x70, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x73, 0x65, 0x6d, 0x69, 0x50, 0x65, 0x61, 0x6b, 0x43,
	0x61, 0x70, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x61, 0x74, 0x53, 0x65, 0x6d, 0x69, 0x50, 0x65, 0x61,
	0x6b, 0x43, 0x61, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x73, 0x61, 0x74, 0x53,
	0x65, 0x6d, 0x69, 0x50, 0x65, 0x61, 0x6b, 0x43, 0x61, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x66,
	0x66, 0x50, 0x65, 0x61, 0x6b, 0x43, 0x61, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x6f, 0x66, 0x66, 0x50, 0x65, 0x61, 0x6b, 0x43, 0x61, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x0b, 0x44, 0x6c,
	0x67, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x6f, 0x63, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f,
	0x63, 0x4e, 0x6f, 0x22, 0x86, 0x02, 0x0a, 0x08, 0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x6f, 0x63, 0x4e, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x77, 0x65,
	0x65, 0x6b, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x77, 0x65, 0x65, 0x6b, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0c,
	0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x05,
	0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x72,
	0x6f, 0x6e, 0x2e, 0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x05, 0x68, 0x6f, 0x75,
	0x72, 0x73, 0x32, 0x83, 0x09, 0x0a, 0x04, 0x43, 0x72, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x0a, 0x51,
	0x75, 0x69, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x13, 0x2e, 0x63, 0x72, 0x6f, 0x6e,
	0x2e, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x2a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x72, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x2e, 0x63, 0x72,
	0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x63, 0x72,
	0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x43, 0x72, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x43, 0x72,
	0x6f, 0x6e, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x72, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x6f,
	0x6e, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x72, 0x6f, 0x6e, 0x12, 0x0c, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x43, 0x72, 0x6f, 0x6e, 0x12,
	0x11, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x43, 0x72, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e,
	0x12, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x52,
	0x73, 0x70, 0x12, 0x30, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x12,
	0x12, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x73, 0x12, 0x11, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x12, 0x11, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e,
	0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x72,
	0x6f, 0x6e, 0x2e, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x52, 0x73, 0x70, 0x12, 0x34,
	0x0a, 0x0b, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x12, 0x14, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f,
	0x6c, 0x69, 0x64, 0x61, 0x79, 0x12, 0x0c, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x0e, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x0e, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x73, 0x70,
	0x12, 0x2e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x42, 0x69,
	0x6c, 0x6c, 0x12, 0x0d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x1a, 0x0d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x73, 0x70,
	0x12, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x19, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x73, 0x70, 0x12, 0x3d, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x36, 0x0a, 0x0d,
	0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x6f, 0x64, 0x79, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x0f,
	0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x31, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x73, 0x70, 0x12, 0x35, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x12, 0x14, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x6c, 0x67,
	0x64, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x10, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x11, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x35, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x12, 0x11, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x44, 0x6c, 0x67, 0x64, 0x48, 0x6f, 0x75,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x44, 0x6c, 0x67, 0x64,
	0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63, 0x72,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cron_proto_rawDescOnce sync.Once
	file_cron_proto_rawDescData = file_cron_proto_rawDesc
)

func file_cron_proto_rawDescGZIP() []byte {
	file_cron_proto_rawDescOnce.Do(func() {
		file_cron_proto_rawDescData = protoimpl.X.CompressGZIP(file_cron_proto_rawDescData)
	})
	return file_cron_proto_rawDescData
}

var file_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_cron_proto_goTypes = []interface{}{
	(*DelReq)(nil),              // 0: cron.DelReq
	(*ResultRsp)(nil),           // 1: cron.ResultRsp
	(*QuickStartReq)(nil),       // 2: cron.QuickStartReq
	(*CronBody)(nil),            // 3: cron.CronBody
	(*CronsReq)(nil),            // 4: cron.CronsReq
	(*CronsRsp)(nil),            // 5: cron.CronsRsp
	(*TodoCronReq)(nil),         // 6: cron.TodoCronReq
	(*CarbonReq)(nil),           // 7: cron.CarbonReq
	(*CarbonRsp)(nil),           // 8: cron.CarbonRsp
	(*AddCarbonReq)(nil),        // 9: cron.AddCarbonReq
	(*WeathersReq)(nil),         // 10: cron.WeathersReq
	(*Weather)(nil),             // 11: cron.Weather
	(*WeathersRsp)(nil),         // 12: cron.WeathersRsp
	(*HolidaysReq)(nil),         // 13: cron.HolidaysReq
	(*Holiday)(nil),             // 14: cron.Holiday
	(*HolidaysRsp)(nil),         // 15: cron.HolidaysRsp
	(*AddHolidaysReq)(nil),      // 16: cron.AddHolidaysReq
	(*PriceReq)(nil),            // 17: cron.PriceReq
	(*PriceRsp)(nil),            // 18: cron.PriceRsp
	(*BillReq)(nil),             // 19: cron.BillReq
	(*BillDetail)(nil),          // 20: cron.BillDetail
	(*BillRsp)(nil),             // 21: cron.BillRsp
	(*AvailableOptionsReq)(nil), // 22: cron.AvailableOptionsReq
	(*AvailableOptionsRsp)(nil), // 23: cron.AvailableOptionsRsp
	(*GetUserOptionReq)(nil),    // 24: cron.GetUserOptionReq
	(*UserOptionBody)(nil),      // 25: cron.UserOptionBody
	(*AddDlgdHourReq)(nil),      // 26: cron.AddDlgdHourReq
	(*DlgdHourReq)(nil),         // 27: cron.DlgdHourReq
	(*DlgdHour)(nil),            // 28: cron.DlgdHour
	(*DlgdHoursRsp)(nil),        // 29: cron.DlgdHoursRsp
}
var file_cron_proto_depIdxs = []int32{
	3,  // 0: cron.CronsRsp.crons:type_name -> cron.CronBody
	11, // 1: cron.WeathersRsp.weathers:type_name -> cron.Weather
	14, // 2: cron.HolidaysRsp.holidays:type_name -> cron.Holiday
	14, // 3: cron.AddHolidaysReq.holidays:type_name -> cron.Holiday
	20, // 4: cron.BillRsp.details:type_name -> cron.BillDetail
	28, // 5: cron.DlgdHoursRsp.hours:type_name -> cron.DlgdHour
	2,  // 6: cron.Cron.QuickStart:input_type -> cron.QuickStartReq
	4,  // 7: cron.Cron.GetCrons:input_type -> cron.CronsReq
	3,  // 8: cron.Cron.AddCron:input_type -> cron.CronBody
	3,  // 9: cron.Cron.UpdateCron:input_type -> cron.CronBody
	0,  // 10: cron.Cron.DeleteCron:input_type -> cron.DelReq
	6,  // 11: cron.Cron.TodoCron:input_type -> cron.TodoCronReq
	7,  // 12: cron.Cron.GetCarbon:input_type -> cron.CarbonReq
	9,  // 13: cron.Cron.AddCarbon:input_type -> cron.AddCarbonReq
	10, // 14: cron.Cron.GetWeathers:input_type -> cron.WeathersReq
	13, // 15: cron.Cron.GetHolidays:input_type -> cron.HolidaysReq
	16, // 16: cron.Cron.AddHolidays:input_type -> cron.AddHolidaysReq
	0,  // 17: cron.Cron.DeleteHoliday:input_type -> cron.DelReq
	17, // 18: cron.Cron.GetPrice:input_type -> cron.PriceReq
	19, // 19: cron.Cron.GetMonthlyBill:input_type -> cron.BillReq
	22, // 20: cron.Cron.GetAvailableOptions:input_type -> cron.AvailableOptionsReq
	24, // 21: cron.Cron.GetUserOption:input_type -> cron.GetUserOptionReq
	25, // 22: cron.Cron.AddUserOption:input_type -> cron.UserOptionBody
	25, // 23: cron.Cron.UpdateUserOption:input_type -> cron.UserOptionBody
	0,  // 24: cron.Cron.DeleteUserOption:input_type -> cron.DelReq
	26, // 25: cron.Cron.AddDlgdHours:input_type -> cron.AddDlgdHourReq
	27, // 26: cron.Cron.ConfirmDlgdHours:input_type -> cron.DlgdHourReq
	27, // 27: cron.Cron.GetDlgdHours:input_type -> cron.DlgdHourReq
	1,  // 28: cron.Cron.QuickStart:output_type -> cron.ResultRsp
	5,  // 29: cron.Cron.GetCrons:output_type -> cron.CronsRsp
	1,  // 30: cron.Cron.AddCron:output_type -> cron.ResultRsp
	1,  // 31: cron.Cron.UpdateCron:output_type -> cron.ResultRsp
	1,  // 32: cron.Cron.DeleteCron:output_type -> cron.ResultRsp
	1,  // 33: cron.Cron.TodoCron:output_type -> cron.ResultRsp
	8,  // 34: cron.Cron.GetCarbon:output_type -> cron.CarbonRsp
	1,  // 35: cron.Cron.AddCarbon:output_type -> cron.ResultRsp
	12, // 36: cron.Cron.GetWeathers:output_type -> cron.WeathersRsp
	15, // 37: cron.Cron.GetHolidays:output_type -> cron.HolidaysRsp
	1,  // 38: cron.Cron.AddHolidays:output_type -> cron.ResultRsp
	1,  // 39: cron.Cron.DeleteHoliday:output_type -> cron.ResultRsp
	18, // 40: cron.Cron.GetPrice:output_type -> cron.PriceRsp
	21, // 41: cron.Cron.GetMonthlyBill:output_type -> cron.BillRsp
	23, // 42: cron.Cron.GetAvailableOptions:output_type -> cron.AvailableOptionsRsp
	25, // 43: cron.Cron.GetUserOption:output_type -> cron.UserOptionBody
	1,  // 44: cron.Cron.AddUserOption:output_type -> cron.ResultRsp
	1,  // 45: cron.Cron.UpdateUserOption:output_type -> cron.ResultRsp
	1,  // 46: cron.Cron.DeleteUserOption:output_type -> cron.ResultRsp
	1,  // 47: cron.Cron.AddDlgdHours:output_type -> cron.ResultRsp
	1,  // 48: cron.Cron.ConfirmDlgdHours:output_type -> cron.ResultRsp
	29, // 49: cron.Cron.GetDlgdHours:output_type -> cron.DlgdHoursRsp
	28, // [28:50] is the sub-list for method output_type
	6,  // [6:28] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cron_proto_init() }
func file_cron_proto_init() {
	if File_cron_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cron_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuickStartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CronsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoCronReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarbonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarbonRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCarbonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeathersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weather); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeathersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolidaysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Holiday); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolidaysRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHolidaysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableOptionsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableOptionsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOptionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOptionBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDlgdHourReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DlgdHourReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DlgdHour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cron_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DlgdHoursRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cron_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cron_proto_goTypes,
		DependencyIndexes: file_cron_proto_depIdxs,
		MessageInfos:      file_cron_proto_msgTypes,
	}.Build()
	File_cron_proto = out.File
	file_cron_proto_rawDesc = nil
	file_cron_proto_goTypes = nil
	file_cron_proto_depIdxs = nil
}
