// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: cron.proto

package cronclient

import (
	"context"

	"seeccloud.com/edscron/cron"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCarbonReq        = cron.AddCarbonReq
	AddDlgdHourReq      = cron.AddDlgdHourReq
	AddHolidaysReq      = cron.AddHolidaysReq
	AvailableOptionsReq = cron.AvailableOptionsReq
	AvailableOptionsRsp = cron.AvailableOptionsRsp
	BillDetail          = cron.BillDetail
	BillReq             = cron.BillReq
	BillRsp             = cron.BillRsp
	CarbonReq           = cron.CarbonReq
	CarbonRsp           = cron.CarbonRsp
	CronBody            = cron.CronBody
	CronsReq            = cron.CronsReq
	CronsRsp            = cron.CronsRsp
	DelReq              = cron.DelReq
	DlgdHour            = cron.DlgdHour
	DlgdHourReq         = cron.DlgdHourReq
	DlgdHoursRsp        = cron.DlgdHoursRsp
	GetUserOptionReq    = cron.GetUserOptionReq
	Holiday             = cron.Holiday
	HolidaysReq         = cron.HolidaysReq
	HolidaysRsp         = cron.HolidaysRsp
	PriceReq            = cron.PriceReq
	PriceRsp            = cron.PriceRsp
	QuickStartReq       = cron.QuickStartReq
	ResultRsp           = cron.ResultRsp
	TodoCronReq         = cron.TodoCronReq
	UserOptionBody      = cron.UserOptionBody
	Weather             = cron.Weather
	WeathersReq         = cron.WeathersReq
	WeathersRsp         = cron.WeathersRsp

	Cron interface {
		// 快速开始
		QuickStart(ctx context.Context, in *QuickStartReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 获取任务列表
		GetCrons(ctx context.Context, in *CronsReq, opts ...grpc.CallOption) (*CronsRsp, error)
		// 新增任务
		AddCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error)
		// 更新任务
		UpdateCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error)
		// 删除任务
		DeleteCron(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 执行任务
		TodoCron(ctx context.Context, in *TodoCronReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 获取碳排因子
		GetCarbon(ctx context.Context, in *CarbonReq, opts ...grpc.CallOption) (*CarbonRsp, error)
		// 新增碳排因子
		AddCarbon(ctx context.Context, in *AddCarbonReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 获取天气预报列表
		GetWeathers(ctx context.Context, in *WeathersReq, opts ...grpc.CallOption) (*WeathersRsp, error)
		// 获取假日列表
		GetHolidays(ctx context.Context, in *HolidaysReq, opts ...grpc.CallOption) (*HolidaysRsp, error)
		// 新增/更新假日
		AddHolidays(ctx context.Context, in *AddHolidaysReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 删除假日
		DeleteHoliday(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 获取电价
		GetPrice(ctx context.Context, in *PriceReq, opts ...grpc.CallOption) (*PriceRsp, error)
		// 获取账单
		GetMonthlyBill(ctx context.Context, in *BillReq, opts ...grpc.CallOption) (*BillRsp, error)
		// 获取用电档案可选项
		GetAvailableOptions(ctx context.Context, in *AvailableOptionsReq, opts ...grpc.CallOption) (*AvailableOptionsRsp, error)
		// 获取用电档案
		GetUserOption(ctx context.Context, in *GetUserOptionReq, opts ...grpc.CallOption) (*UserOptionBody, error)
		// 新增用电档案
		AddUserOption(ctx context.Context, in *UserOptionBody, opts ...grpc.CallOption) (*ResultRsp, error)
		// 更新用电档案
		UpdateUserOption(ctx context.Context, in *UserOptionBody, opts ...grpc.CallOption) (*ResultRsp, error)
		// 删除用电档案
		DeleteUserOption(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 新增用电时段
		AddDlgdHours(ctx context.Context, in *AddDlgdHourReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 确认用电时段
		ConfirmDlgdHours(ctx context.Context, in *DlgdHourReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 查询用电时段
		GetDlgdHours(ctx context.Context, in *DlgdHourReq, opts ...grpc.CallOption) (*DlgdHoursRsp, error)
	}

	defaultCron struct {
		cli zrpc.Client
	}
)

func NewCron(cli zrpc.Client) Cron {
	return &defaultCron{
		cli: cli,
	}
}

// 快速开始
func (m *defaultCron) QuickStart(ctx context.Context, in *QuickStartReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.QuickStart(ctx, in, opts...)
}

// 获取任务列表
func (m *defaultCron) GetCrons(ctx context.Context, in *CronsReq, opts ...grpc.CallOption) (*CronsRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetCrons(ctx, in, opts...)
}

// 新增任务
func (m *defaultCron) AddCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.AddCron(ctx, in, opts...)
}

// 更新任务
func (m *defaultCron) UpdateCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.UpdateCron(ctx, in, opts...)
}

// 删除任务
func (m *defaultCron) DeleteCron(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.DeleteCron(ctx, in, opts...)
}

// 执行任务
func (m *defaultCron) TodoCron(ctx context.Context, in *TodoCronReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.TodoCron(ctx, in, opts...)
}

// 获取碳排因子
func (m *defaultCron) GetCarbon(ctx context.Context, in *CarbonReq, opts ...grpc.CallOption) (*CarbonRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetCarbon(ctx, in, opts...)
}

// 新增碳排因子
func (m *defaultCron) AddCarbon(ctx context.Context, in *AddCarbonReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.AddCarbon(ctx, in, opts...)
}

// 获取天气预报列表
func (m *defaultCron) GetWeathers(ctx context.Context, in *WeathersReq, opts ...grpc.CallOption) (*WeathersRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetWeathers(ctx, in, opts...)
}

// 获取假日列表
func (m *defaultCron) GetHolidays(ctx context.Context, in *HolidaysReq, opts ...grpc.CallOption) (*HolidaysRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetHolidays(ctx, in, opts...)
}

// 新增/更新假日
func (m *defaultCron) AddHolidays(ctx context.Context, in *AddHolidaysReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.AddHolidays(ctx, in, opts...)
}

// 删除假日
func (m *defaultCron) DeleteHoliday(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.DeleteHoliday(ctx, in, opts...)
}

// 获取电价
func (m *defaultCron) GetPrice(ctx context.Context, in *PriceReq, opts ...grpc.CallOption) (*PriceRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetPrice(ctx, in, opts...)
}

// 获取账单
func (m *defaultCron) GetMonthlyBill(ctx context.Context, in *BillReq, opts ...grpc.CallOption) (*BillRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetMonthlyBill(ctx, in, opts...)
}

// 获取用电档案可选项
func (m *defaultCron) GetAvailableOptions(ctx context.Context, in *AvailableOptionsReq, opts ...grpc.CallOption) (*AvailableOptionsRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetAvailableOptions(ctx, in, opts...)
}

// 获取用电档案
func (m *defaultCron) GetUserOption(ctx context.Context, in *GetUserOptionReq, opts ...grpc.CallOption) (*UserOptionBody, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetUserOption(ctx, in, opts...)
}

// 新增用电档案
func (m *defaultCron) AddUserOption(ctx context.Context, in *UserOptionBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.AddUserOption(ctx, in, opts...)
}

// 更新用电档案
func (m *defaultCron) UpdateUserOption(ctx context.Context, in *UserOptionBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.UpdateUserOption(ctx, in, opts...)
}

// 删除用电档案
func (m *defaultCron) DeleteUserOption(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.DeleteUserOption(ctx, in, opts...)
}

// 新增用电时段
func (m *defaultCron) AddDlgdHours(ctx context.Context, in *AddDlgdHourReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.AddDlgdHours(ctx, in, opts...)
}

// 确认用电时段
func (m *defaultCron) ConfirmDlgdHours(ctx context.Context, in *DlgdHourReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.ConfirmDlgdHours(ctx, in, opts...)
}

// 查询用电时段
func (m *defaultCron) GetDlgdHours(ctx context.Context, in *DlgdHourReq, opts ...grpc.CallOption) (*DlgdHoursRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetDlgdHours(ctx, in, opts...)
}
