// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: cron.proto

package cronclient

import (
	"context"

	"seeccloud.com/edscron/cron"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCarbonReq     = cron.AddCarbonReq
	AddHolidaysReq   = cron.AddHolidaysReq
	BillDetail       = cron.BillDetail
	BillReq          = cron.BillReq
	BillRsp          = cron.BillRsp
	CarbonReq        = cron.CarbonReq
	CarbonRsp        = cron.CarbonRsp
	CronBody         = cron.CronBody
	CronsReq         = cron.CronsReq
	CronsRsp         = cron.CronsRsp
	DelReq           = cron.DelReq
	EnergyOptionsReq = cron.EnergyOptionsReq
	EnergyOptionsRsp = cron.EnergyOptionsRsp
	Holiday          = cron.Holiday
	HolidaysReq      = cron.HolidaysReq
	HolidaysRsp      = cron.HolidaysRsp
	PriceReq         = cron.PriceReq
	PriceRsp         = cron.PriceRsp
	ResultRsp        = cron.ResultRsp
	TodoCronReq      = cron.TodoCronReq
	Weather          = cron.Weather
	WeathersReq      = cron.WeathersReq
	WeathersRsp      = cron.WeathersRsp

	Cron interface {
		// 获取能源可选项
		GetEnergyOptions(ctx context.Context, in *EnergyOptionsReq, opts ...grpc.CallOption) (*EnergyOptionsRsp, error)
		// 获取任务列表
		GetCrons(ctx context.Context, in *CronsReq, opts ...grpc.CallOption) (*CronsRsp, error)
		// 创建任务
		AddCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error)
		// 更新任务
		UpdateCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error)
		// 删除任务
		DeleteCron(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 执行任务
		TodoCron(ctx context.Context, in *TodoCronReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 获取碳排因子
		GetCarbon(ctx context.Context, in *CarbonReq, opts ...grpc.CallOption) (*CarbonRsp, error)
		// 创建碳排因子
		AddCarbon(ctx context.Context, in *AddCarbonReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 获取天气预报列表
		GetWeathers(ctx context.Context, in *WeathersReq, opts ...grpc.CallOption) (*WeathersRsp, error)
		// 获取假日列表
		GetHolidays(ctx context.Context, in *HolidaysReq, opts ...grpc.CallOption) (*HolidaysRsp, error)
		// 创建/更新假日
		AddHolidays(ctx context.Context, in *AddHolidaysReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 删除假日
		DeleteHoliday(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error)
		// 获取电价
		GetPrice(ctx context.Context, in *PriceReq, opts ...grpc.CallOption) (*PriceRsp, error)
		// 获取账单
		GetBill(ctx context.Context, in *BillReq, opts ...grpc.CallOption) (*BillRsp, error)
	}

	defaultCron struct {
		cli zrpc.Client
	}
)

func NewCron(cli zrpc.Client) Cron {
	return &defaultCron{
		cli: cli,
	}
}

// 获取能源可选项
func (m *defaultCron) GetEnergyOptions(ctx context.Context, in *EnergyOptionsReq, opts ...grpc.CallOption) (*EnergyOptionsRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetEnergyOptions(ctx, in, opts...)
}

// 获取任务列表
func (m *defaultCron) GetCrons(ctx context.Context, in *CronsReq, opts ...grpc.CallOption) (*CronsRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetCrons(ctx, in, opts...)
}

// 创建任务
func (m *defaultCron) AddCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.AddCron(ctx, in, opts...)
}

// 更新任务
func (m *defaultCron) UpdateCron(ctx context.Context, in *CronBody, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.UpdateCron(ctx, in, opts...)
}

// 删除任务
func (m *defaultCron) DeleteCron(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.DeleteCron(ctx, in, opts...)
}

// 执行任务
func (m *defaultCron) TodoCron(ctx context.Context, in *TodoCronReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.TodoCron(ctx, in, opts...)
}

// 获取碳排因子
func (m *defaultCron) GetCarbon(ctx context.Context, in *CarbonReq, opts ...grpc.CallOption) (*CarbonRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetCarbon(ctx, in, opts...)
}

// 创建碳排因子
func (m *defaultCron) AddCarbon(ctx context.Context, in *AddCarbonReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.AddCarbon(ctx, in, opts...)
}

// 获取天气预报列表
func (m *defaultCron) GetWeathers(ctx context.Context, in *WeathersReq, opts ...grpc.CallOption) (*WeathersRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetWeathers(ctx, in, opts...)
}

// 获取假日列表
func (m *defaultCron) GetHolidays(ctx context.Context, in *HolidaysReq, opts ...grpc.CallOption) (*HolidaysRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetHolidays(ctx, in, opts...)
}

// 创建/更新假日
func (m *defaultCron) AddHolidays(ctx context.Context, in *AddHolidaysReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.AddHolidays(ctx, in, opts...)
}

// 删除假日
func (m *defaultCron) DeleteHoliday(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*ResultRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.DeleteHoliday(ctx, in, opts...)
}

// 获取电价
func (m *defaultCron) GetPrice(ctx context.Context, in *PriceReq, opts ...grpc.CallOption) (*PriceRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetPrice(ctx, in, opts...)
}

// 获取账单
func (m *defaultCron) GetBill(ctx context.Context, in *BillReq, opts ...grpc.CallOption) (*BillRsp, error) {
	client := cron.NewCronClient(m.cli.Conn())
	return client.GetBill(ctx, in, opts...)
}
